language: php

php:
  - 5.6
  - 7.0

sudo: false

cache:
  directories:
    - ~/.composer/cache

before_install:
  - cp .travis.php_$(phpenv version-name).ini ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - export COMPOSER_ROOT_VERSION=dev-master
  - composer install --no-progress --prefer-dist

script: ./bin/phpunit

addons:
  code_climate:
    repo_token: 1a9830b7101c496d4b98ee832ae6202bc4480dd79c825bb1bbb69a2a38d4e2cd

after_script:
  - ./bin/test-reporter
