language: php

php:
  - 5.6

sudo: false

cache:
  directories:
    - ~/.composer/cache

before_install:
  - phpenv config-add .travis.php.ini

install:
  - composer install --no-progress --prefer-dist

script: ./bin/phpunit

addons:
  code_climate:
    repo_token: 1a9830b7101c496d4b98ee832ae6202bc4480dd79c825bb1bbb69a2a38d4e2cd

after_script:
  - ./bin/test-reporter
