parameters:
    open_orchestra.annotation_reader.class: Doctrine\Common\Annotations\AnnotationReader
    open_orchestra.annotation_file_locator.class: Metadata\Driver\FileLocator
    open_orchestra.annotation_cache.class: Metadata\Cache\FileCache
    open_orchestra.annotation_search.class: OpenOrchestra\Mapping\Annotations\Search
    open_orchestra.annotation_search_reader.class: OpenOrchestra\Mapping\Reader\SearchMappingReader
    open_orchestra.annotation_search.metadata_factory.class: Metadata\MetadataFactory
    open_orchestra.annotation_search.annotation_driver.class: OpenOrchestra\Mapping\Metadata\Driver\AnnotationDriver
    open_orchestra.annotation_search.yaml_driver.class: OpenOrchestra\Mapping\Metadata\Driver\YamlDriver
    open_orchestra.annotation_search.xml_driver.class: OpenOrchestra\Mapping\Metadata\Driver\XmlDriver
    open_orchestra.annotation_search.driver_chain.class: Metadata\Driver\DriverChain
    open_orchestra.annotation_search.mergeable_class_metadata_factory.class: OpenOrchestra\Mapping\Metadata\MergeableClassMetadataFactory
    open_orchestra.annotation_search.property_search_metadata_factory.class: OpenOrchestra\Mapping\Metadata\PropertySearchMetadataFactory

services:
    open_orchestra.annotation_reader:
        class: %open_orchestra.annotation_reader.class%
    open_orchestra.annotation_file_locator:
        class: %open_orchestra.annotation_file_locator.class%
        arguments:
            - []
    open_orchestra.annotation_cache:
        class: %open_orchestra.annotation_cache.class%
        arguments:
            - []
    open_orchestra.annotation_search.mergeable_class_metadata_factory:
        class: %open_orchestra.annotation_search.mergeable_class_metadata_factory.class%
    open_orchestra.annotation_search.property_search_metadata_factory:
        class: %open_orchestra.annotation_search.property_search_metadata_factory.class%
    open_orchestra.annotation_search.annotation_driver:
        class: %open_orchestra.annotation_search.annotation_driver.class%
        arguments:
            - @open_orchestra.annotation_reader
            - @open_orchestra.annotation_search.property_search_metadata_factory
            - @open_orchestra.annotation_search.mergeable_class_metadata_factory
            - %open_orchestra.annotation_search.class%
    open_orchestra.annotation_search.yaml_driver:
        class: %open_orchestra.annotation_search.yaml_driver.class%
        arguments:
            - @open_orchestra.annotation_file_locator
            - @open_orchestra.annotation_search.property_search_metadata_factory
            - @open_orchestra.annotation_search.mergeable_class_metadata_factory
    open_orchestra.annotation_search.xml_driver:
        class: %open_orchestra.annotation_search.xml_driver.class%
        arguments:
            - @open_orchestra.annotation_file_locator
            - @open_orchestra.annotation_search.property_search_metadata_factory
            - @open_orchestra.annotation_search.mergeable_class_metadata_factory
    open_orchestra.annotation_search.driver_chain:
        class: %open_orchestra.annotation_search.driver_chain.class%
        calls:
            - [ addDriver, [@open_orchestra.annotation_search.yaml_driver]]
            - [ addDriver, [@open_orchestra.annotation_search.xml_driver]]
            - [ addDriver, [@open_orchestra.annotation_search.annotation_driver]]
    open_orchestra.annotation_search.metadata_factory:
        class: %open_orchestra.annotation_search.metadata_factory.class%
        arguments:
            - @open_orchestra.annotation_search.driver_chain
        calls:
            - [ setCache, [@open_orchestra.annotation_cache]]
    open_orchestra.annotation_search_reader:
        class: %open_orchestra.annotation_search_reader.class%
        arguments:
            - @open_orchestra.annotation_search.metadata_factory
