parameters:
    open_orchestra.transformer.lucene_to_bdd.class: OpenOrchestra\Transformer\LuceneToBddTransformer

services:
    open_orchestra.transformer.lucene_to_bdd:
        class: %open_orchestra.transformer.lucene_to_bdd.class%
