parameters:
    open_orchestra.transformer.boolean_to_bdd.class: OpenOrchestra\Transformer\ConditionFromBooleanToMongoTransformer
services:
    open_orchestra.transformer.boolean_to_bdd:
        class: %open_orchestra.transformer.boolean_to_bdd.class%
        deprecated: 'The "%service_id%" service is deprecated. Use " open_orchestra_model.transformer.boolean_to_bdd" instead'
